WITH countries (iso, country) AS (
VALUES ('id', 'Indonesia'),
('br', 'Brazil'),
('ru', 'Russia'),
('ng', 'Nigeria'),

('vn', 'Vietnam'),
('ch', 'Switzerland'),
('mm', 'Myanmar'),
('th', 'Thailand'),
('uz', 'Uzbekistan'),
('cn', 'China'),
('na', 'Namibia'),
('jm', 'Jamaica'),
('pt', 'Portugal'),
('by', 'Belarus'),
('kz', 'Kazakhstan'),
('ph', 'Philippines'),
('ve', 'Venezuela'),
('in', 'India'),
('pk', 'Pakistan'),
('lk', 'Sri Lanka'),
('bd', 'Bangladesh'),
('np', 'Nepal'),
('bo', 'Bolivia'),
('za', 'South Africa'),
('mx', 'Mexico'),
('es', 'Spain'),
('co', 'Colombia'),
('zw', 'Zimbabwe'),
('py', 'Paraguay'),
('tz', 'Tanzania'),
('uy', 'Uruguay'),
('kh', 'Cambodia'),
('la', 'Laos'),
('om', 'Oman'),
('ae', 'United Arab Emirates'),
('eg', 'Egypt'),
('ua', 'Ukraine'),
('ng', 'Nigeria'),
('am', 'Armenia'),
('pe', 'Peru'),
('cl', 'Chile'),
('ar', 'Argentina'),
('md', 'Moldova'),
('gh', 'Ghana'),
('ke', 'Kenya'),
('ec', 'Ecuador')

)